### PR TITLE
fix(session-mysql): commit writes when auto-commit is disabled

### LINKED ISSUE #1087: [Bug]: MysqlSession Can Not Save New Sessions when auto-commit=false
**<u>AgentScope-Java is an open-source project. To involve a broader community, we recommend asking your questions in English.</u>**

**Describe the bug**
`MysqlSession.save(SessionKey sessionKey, String key, List<? extends State> values)` has inconsistent transaction behavior between the "full rewrite" branch and the "incremental append" branch.

full rewrite controls transaction commit manually:

https://github.com/agentscope-ai/agentscope-java/blob/0f48e3fa0539a0432b16c3126096a020c311aace/agentscope-extensions/agentscope-extensions-session-mysql/src/main/java/io/agentscope/core/session/mysql/MysqlSession.java#L361-L379

whereas insert new items does not commit explicitly

https://github.com/agentscope-ai/agentscope-java/blob/0f48e3fa0539a0432b16c3126096a020c311aace/agentscope-extensions/agentscope-extensions-session-mysql/src/main/java/io/agentscope/core/session/mysql/MysqlSession.java#L485-L511

The use of transaction and auto-commit should be more consistent. And `needsFullRewrite` path changes the auto-commit behavior of the connection it gets.

**To Reproduce**

1. Set auto-commit to false
```java
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: false
```

2. Save a new session
MysqlSession saveSession = new MysqlSession()
agent.saveTo(saveSession, sessionId);

3. No new record is inserted

**Environment (please complete the following information):**

- AgentScope-Java Version: 1.0.10
- Java Version:17
- OS: windows

### PR DESCRIPTION
**Pull request by Xiaozhiyao**
## AgentScope-Java Version

1.0.11

## Description

Fixes：MysqlSession Can Not Save New Sessions when auto-commit=false #1087 
- use explicit transaction handling for write methods
- commit writes for save/delete/clear/truncate
- restore the original `autoCommit` state
- add regression tests

Tests:
- `mvn test`
- `mvn -pl "agentscope-extensions/agentscope-extensions-session-mysql" -am test "-Dtest=MysqlSessionTest,MysqlSessionE2ETest"`

Fixes #1087

## Checklist

- [x] Code has been formatted with `mvn spotless:apply`
- [x] All tests are passing (`mvn test`)
- [x] Javadoc comments are complete and follow project conventions
- [ ] Related documentation has been updated (not applicable for this internal bug fix)
- [x] Code is ready for review

### CODE REVIEW

**Comment by Xiaozhiyao** [comment]
Hi @LearningGp  , sorry to ping you. Could you please take a look when you have a moment? Thanks

File: agentscope-extensions/agentscope-extensions-session-mysql/src/main/java/io/agentscope/core/session/mysql/MysqlSession.java [hunk 1]
```diff
@@ -730,12 +771,17 @@ public int clearAllSessions() {
     public int truncateAllSessions() {
         String clearSql = "TRUNCATE TABLE " + getFullTableName();
```
Comment (LearningGp) [inline agentscope-extensions/agentscope-extensions-session-mysql/src/main/java/io/agentscope/core/session/mysql/MysqlSession.java:776]: TRUNCATE triggers an implicit commit in MySQL and isn't rollbackable, making executeInWriteTransaction redundant. To avoid misleading maintainers, please either execute it directly or document this DDL behavior in the Javadoc.

**Review by LearningGp — CHANGES_REQUESTED** [review]

File: agentscope-extensions/agentscope-extensions-session-mysql/src/main/java/io/agentscope/core/session/mysql/MysqlSession.java (hunk 1 above)
Comment (Xiaozhiyao) [reply agentscope-extensions/agentscope-extensions-session-mysql/src/main/java/io/agentscope/core/session/mysql/MysqlSession.java:776]: Updated `truncateAllSessions()` to execute `TRUNCATE TABLE` directly and documented the MySQL DDL behavior in Javadoc. Also updated the related unit test and reran the session-mysql test suite successfully.

**Review by LearningGp — APPROVED** [review]
LGTM
