### PR TITLE
fix(ReActAgent): preserve user chunk callback when using copied toolkit

### LINKED ISSUE #870: [Bug]:Toolkit#setChunkCallback not triggered due to missing callback invocation in AgentScope 1.0.9
1、标题: 在 AgentScope 1.0.9 中 `Toolkit#setChunkCallback` 没有触发回调

2、Bug描述

在 AgentScope 1.0.9 中，通过Toolkit#setChunkCallback，设置的 callback 在 tool 执行时没有被触发。

Tool 可以正常执行，但 callback 函数不会被调用。

3、To Reproduce（如何复现）

```java
public class DemoToolService {
    @Tool(description = "生成数据")
    public ToolResultBlock generate(@ToolParam(name = "count") int count, ToolEmitter emitter) {  // 自动注入，无需 @ToolParam
        for (int i = 0; i < count; i++) {
            emitter.emit(ToolResultBlock.text("进度 " + i));
        }
        return ToolResultBlock.text("完成");
    }
}

public class ToolEmitterChunkCallBack implements BiConsumer<ToolUseBlock, ToolResultBlock> {
    @Override
    public void accept(ToolUseBlock toolUseBlock, ToolResultBlock toolResultBlock) {
        System.out.println(toolUseBlock.getName());
        System.out.println(toolUseBlock.getContent());
        System.out.println(toolResultBlock.getOutput());
    }
}

public class ToolEmitterDemo {
    public static void main(String[] args) {
        
        DashScopeChatModel chatModel = DashScopeChatModel.builder()
                .apiKey(System.getenv("DASH_SCOPE_API_KEY"))
                .modelName("qwen3-max")
                .build();

        Toolkit toolkit = new Toolkit();
        toolkit.registerTool(new WeatherToolService());
        toolkit.setChunkCallback(new ToolEmitterChunkCallBack());

        ReActAgent agent = ReActAgent.builder()
                .name("Assistant")
                .sysPrompt("你是一个有帮助的 AI 助手。")
                .model(chatModel)
                .toolkit(toolkit)
                .build();

        // 创建用户消息
        Msg userMsg = Msg.builder().textContent("生成3个数据").build();
        // 调用智能体
        Mono<Msg> msgMono = agent.call(userMsg);
        // 阻塞等待回复
        Msg response = msgMono.block();
        // 打印回复
        System.out.println(response.getTextContent());
    }
}
```

运行结果

```java
ToolEmitterChunkCallBack never prints
```

4、Expected behavior（期望行为）

```java
当 tool 执行时，setChunkCallback 设置的 callback 应该被触发，用于接收 tool 的执行过程信息。

generate {"count": 3} [进度 0]
generate {"count": 3} [进度 1]
generate {"count": 3} [进度 2]
```

5、 Environment（运行环境）

```java
AgentScope Version: 1.0.9
Java Version: 21
OS: macOS
Model: DashScope qwen3-max
```

5.1、Maven 配置

```java
    <dependencies>
        <dependency>
            <groupId>io.agentscope</groupId>
            <artifactId>agentscope</artifactId>
            <version>1.0.9</version>
        </dependency>

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.4.14</version>
        </dependency>
    </dependencies>
```

6、Additional context（额外信息）

agentscope:1.0.8 可正常回调执行

7、Root Cause

step1: 入口执行

```java
执行 Msg response = msgMono.block();

随后进入：ReActAgent#acting
```

Step 2：注册 ChunkCallback

```java
toolkit.setChunkCallback((toolUse, chunk) -> notifyActingChunk(toolUse, chunk).subscribe());

调用链如下：
ReActAgent#acting
    ↓
Toolkit#setChunkCallback
    ↓
ToolExecutor#setChunkCallback

最终 callback 被保存到 ToolExecutor 中：
private BiConsumer<ToolUseBlock, ToolResultBlock> chunkCallback;
```

Step 3：Tool 执行时创建 ToolEmitter

```java
在 ToolExecutor#executeCore 中执行工具时，会创建 ToolEmitter：
ToolEmitter toolEmitter = new DefaultToolEmitter(toolCall, chunkCallback);

随后构造执行参数：
ToolCallParam executionParam =
        ToolCallParam.builder()
                .toolUseBlock(toolCall)
                .input(mergedInput)
                .agent(param.getAgent())
                .context(finalContext)
                .emitter(toolEmitter)
                .build();
                
toolEmitter 被传递到 tool 执行流程中。
```

Step 4：ToolEmitter 自动注入到 Tool 方法

```java
在 ToolMethodInvoker#invokeAsync 中，如果 Tool 方法声明了 ToolEmitter 参数，会自动注入：

if (param.getType() == ToolEmitter.class) {
    args[i] = emitter;
}
```

Step 5：callback 触发依赖 ToolEmitter.emit()

```java
真正触发 callback 的逻辑在：DefaultToolEmitter#emit

public void emit(ToolResultBlock chunk) {
    if (chunkCallback != null && chunk != null) {
        chunkCallback.accept(toolUseBlock, chunk);
    }
}

此时：并非设置chunkCallback
```

### PR DESCRIPTION
**Pull request by JGoP-L**
## AgentScope-Java Version

1.0.10-SNAPSHOT

## Description

Fixes #870.

Previously, when a user configured a chunk callback via `Toolkit#setChunkCallback(...)` and then passed that toolkit into `ReActAgent.builder().toolkit(toolkit).build()`, the callback could be overwritten by the internal callback registered by `ReActAgent` during tool execution.

This PR separates user-defined chunk callbacks from framework-internal chunk callbacks so both can work together:
- preserve user callbacks across `Toolkit.copy()`
- keep `ActingChunkEvent` emission in `ReActAgent`
- add a regression test in `ToolEmitterIntegrationTest`

### How to test

```bash
mvn -pl agentscope-core -Dtest=ToolEmitterIntegrationTest test

### CODE REVIEW

File: agentscope-core/src/main/java/io/agentscope/core/tool/ToolExecutor.java [hunk 1]
```diff
@@ -92,10 +93,41 @@ class ToolExecutor {
...
+     */
+    private BiConsumer<ToolUseBlock, ToolResultBlock> getEffectiveChunkCallback() {
+        if (internalChunkCallback == null) {
+            return userChunkCallback;
+        }
+        if (userChunkCallback == null) {
+            return internalChunkCallback;
+        }
+        return (toolUse, chunk) -> {
+            internalChunkCallback.accept(toolUse, chunk);
```
Comment (LearningGp) [inline agentscope-core/src/main/java/io/agentscope/core/tool/ToolExecutor.java]: In the composite callback of getEffectiveChunkCallback(), if internalChunkCallback.accept() throws an exception, userChunkCallback will not be executed. While the internal callback currently uses .subscribe() to handle Mono errors, unexpected synchronous exceptions (e.g., NPE) will still cause the user callback to be silently skipped. Should we wrap these in try-catch blocks for isolation to ensure they don't interfere with each other?

Comment (JGoP-L) [reply agentscope-core/src/main/java/io/agentscope/core/tool/ToolExecutor.java]: Good catch. I agree that synchronous exceptions in one callback should not prevent the other callback from running.

I updated `ToolExecutor#getEffectiveChunkCallback()` so both internal and user chunk callbacks are invoked in isolation with separate `try-catch` handling. This ensures:
- internal callback failures do not block the user callback
- user callback failures do not interrupt tool execution
- the same protection also applies when only one callback is present

I also added regression coverage in `ToolEmitterIntegrationTest` for:
- internal callback failure does not block user callback
- user callback failure does not interrupt tool execution
- internal callback failure does not interrupt tool execution
