### PR TITLE
fix(rag): Add missing payload for ElasticsearchStore

### LINKED ISSUE #1044: [Bug]:
**<u>AgentScope-Java is an open-source project. To involve a broader community, we recommend asking your questions in English.</u>**

**Describe the bug**

**To Reproduce**

1. You code
2. How to execute
3. See error

**Expected behavior**

**Error messages**
Detailed error messages.

**Environment (please complete the following information):**

- AgentScope-Java Version: [e.g. 1.0.9, check your pom.xml dependency version or run `mvn dependency:tree | grep agentscope-parent:pom`(only mac/linux)]
- Java Version: [e.g. 17]
- OS: [e.g. macos, windows]

**Additional context**

### PR DESCRIPTION
**Pull request by guanxuc**
## AgentScope-Java Version

1.0.11

## Description

* Fixes: #1044 
* Add missing payload for `ElasticsearchStore`

## Checklist

Please check the following items before code is ready to be reviewed.

- [x]  Code has been formatted with `mvn spotless:apply`
- [x]  All tests are passing (`mvn test`)
- [x]  Javadoc comments are complete and follow project conventions
- [x]  Related documentation has been updated (e.g. links, examples, etc.)
- [x]  Code is ready for review

### CODE REVIEW

**Review by LearningGp — CHANGES_REQUESTED** [review]
Write path looks good (L408-L411), but mapFromEsHit() misses the payload. It's still using the 3-arg constructor instead of retrieving the payload from the ES hit source.

**Comment by guanxuc** [comment]
@LearningGp Thanks for your review, I have updated the code.

File: agentscope-extensions/agentscope-extensions-rag-simple/src/main/java/io/agentscope/core/rag/store/ElasticsearchStore.java [hunk 1]
```diff
@@ -363,6 +365,7 @@ private void ensureIndex() throws VectorStoreException {
             properties.put(FIELD_CHUNK_ID, idProperty);
             properties.put(FIELD_CONTENT, contentProperty);
             properties.put(FIELD_VECTOR, vectorProperty);
+            properties.put(FIELD_PAYLOAD, contentProperty);
```
Comment (LearningGp) [inline agentscope-extensions/agentscope-extensions-rag-simple/src/main/java/io/agentscope/core/rag/store/ElasticsearchStore.java:368]: Regarding the mapping of payload to contentProperty: since the payload typically contains structured metadata (e.g., {"filename": "report.pdf", "tags": ["finance", "Q4"]}), wouldn't it be more appropriate to use object or flattened types?

**Review by LearningGp — COMMENTED** [review]
LGTM

File: agentscope-extensions/agentscope-extensions-rag-simple/src/main/java/io/agentscope/core/rag/store/ElasticsearchStore.java (hunk 1 above)
Comment (guanxuc) [reply agentscope-extensions/agentscope-extensions-rag-simple/src/main/java/io/agentscope/core/rag/store/ElasticsearchStore.java:368]: Please take a look at `ElasticsearchStore#mapToEsDocument(L421-L424)`, I use json string to save payload to prevent object field explosion deserialization issues.

**Review by LearningGp — APPROVED** [review]
