### PR TITLE
fix(skill): Remove Windows reserved characters from FileSystemSkillRepository source (#947)

### LINKED ISSUE #947: [Bug]:java.nio.file.InvalidPathException: Illegal char <:> at index 25
17:13:08.598 [http-nio-8080-exec-5] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.nio.file.InvalidPathException: Illegal char <:> at index 25: kafka-sampling_filesystem:.agents_skills] with root cause
java.nio.file.InvalidPathException: Illegal char <:> at index 25: kafka-sampling_filesystem:.agents_skills 

agentscope自己生成的路径再windows上运行报错，这应该算个bug

### PR DESCRIPTION
**Pull request by huangxinchuan**
## Problem
  On Windows systems, `FileSystemSkillRepository.buildDefaultSourceSuffix()` generates source strings containing Windows reserved characters (e.g., `C:` drive colon), causing `InvalidPathException` when AgentScope tries to
  create files or directories with these names.

  Error example from #947:
  java.nio.file.InvalidPathException: Illegal char <:> at index 25: kafka-sampling_filesystem:.agents_skills

  ## Solution
  Remove all Windows reserved characters (`\`, `/`, `:`, `*`, `?`, `"`, `<`, `>`, `|`) from the generated source suffix using regex replacement.

  ## Changes
  - Modified `buildDefaultSourceSuffix()` in `FileSystemSkillRepository.java`
  - Added regex to strip Windows reserved characters from the source string

  ## Testing
  - Existing test `testSave_SourceHasNoColon` now passes on Windows
  - The fix is backward compatible (non-Windows systems unaffected)

  Fixes #947

  ---

### CODE REVIEW

**Comment by huangxinchuan** [comment]
@cla-assistant recheck

  I have updated the commit author from company email to my personal GitHub email (87484734@qq.com).

  The old commits with "黄新传 <643160@ky-tech.com.cn>" have been force-pushed and replaced.
  Please recheck the CLA status for the current commits.

  Thanks!

**Comment by huangxinchuan** [comment]
Hi @AlbumenJ and team,

  This PR is ready for review. It fixes the Windows path compatibility issue reported in #947.

  **Summary of changes:**
  - `FileSystemSkillRepository`: Remove Windows reserved characters (`\ / : * ? " < > |`) from the generated source suffix
  - `GitSkillRepository`: Change source prefix from `git:` to `git-` and apply the same character filtering
  - Added comprehensive unit tests for both repositories

  **Verification:**
  - ✅ All CI checks passed
  - ✅ CLA signed
  - ✅ Fixes #947 (InvalidPathException on Windows)

  The fix ensures that skill repository sources don't contain Windows reserved characters, which previously caused `InvalidPathException` when running on Windows systems.

  Please let me know if you need any changes or have questions. Thanks for your time!

**Comment by LearningGp** [comment]
@fang-tech PTAL

File: agentscope-core/src/main/java/io/agentscope/core/skill/repository/FileSystemSkillRepository.java [hunk 1]
```diff
@@ -166,11 +166,16 @@ private String buildDefaultSourceSuffix() {
             return "unknown";
         }
 
+        String suffix;
         if (parent == null || parent.getFileName() == null) {
-            return fileName.toString();
+            suffix = fileName.toString();
```
Comment (fang-tech) [inline agentscope-core/src/main/java/io/agentscope/core/skill/repository/FileSystemSkillRepository.java]: What is the reason for this modification? In fact, the current version does not contain the : character in the associated issue.

File: agentscope-extensions/agentscope-extensions-skill-git-repository/src/main/java/io/agentscope/core/skill/repository/GitSkillRepository.java [hunk 2]
```diff
@@ -335,7 +335,13 @@ public String getSource() {
...
     private String buildDefaultSource() {
         String repoIdentifier = extractRepositoryIdentifier(remoteUrl);
-        return branch != null ? "git:" + repoIdentifier + "@" + branch : "git:" + repoIdentifier;
+        // Use hyphen instead of colon to avoid Windows path issues
+        String source =
+                branch != null ? "git-" + repoIdentifier + "@" + branch : "git-" + repoIdentifier;
+        // Remove Windows reserved characters that might be in branch names
+        // Note: forward slash (/) is kept as it's valid in source identifiers (owner/repo format)
+        // and is not a Windows reserved character in the context of file name
+        return source.replaceAll("[\\\\:*?\"<>|]", "");
```
Comment (fang-tech) [inline agentscope-extensions/agentscope-extensions-skill-git-repository/src/main/java/io/agentscope/core/skill/repository/GitSkillRepository.java]: replace with "-" instead of ""

Comment (huangxinchuan) [reply agentscope-extensions/agentscope-extensions-skill-git-repository/src/main/java/io/agentscope/core/skill/repository/GitSkillRepository.java]: Thank you @fang-tech for the review! I have addressed both comments:

  ▎ 1. FileSystemSkillRepository.java:171 - You are right. The : character filtering was redundant since the source prefix already uses filesystem- instead of filesystem:. I have reverted the unnecessary changes.
  ▎ 2. GitSkillRepository.java:344 - Changed replaceAll to use - instead of "" (empty string) as you suggested.

  ▎ The changes have been pushed. Could you please take another look? Thanks!

**Review by LearningGp — APPROVED** [review]
