### PR TITLE
fix(tool): prevent SubAgent name collisions for unsupported characters via deterministic hashing

### LINKED ISSUE #1140: [Bug]:智能体to工具只保留最后一个的bug，注册多个时，前面的会丢
智能体to工具只保留最后一个的bug，注册多个时，前面的会丢

--- 代码
ReActAgent sxls = ReActAgent.builder()
                .name("数学老师")
                .sysPrompt("你是一个数学老师")
                .description("只处理数学相关的问题")
                .hooks(List.of(
                        new LoggingHook(),new AssistantToUser()
                ))
                .model(model)
                .memory(new InMemoryMemory())
                .build();
        ReActAgent ywls = ReActAgent.builder()
                .name("语文老师")
                .sysPrompt("你是一个语文老师")
                .description("只处理语文相关问题")
                .hooks(List.of(
                        new LoggingHook(),new AssistantToUser()
                ))
                .model(model)
                .memory(new InMemoryMemory())
                .build();
        ReActAgent yyls = ReActAgent.builder()
                .name("英语老师")
                .sysPrompt("你是一个英语老师")
                .description("只处理英语相关问题")
                .hooks(List.of(
                        new LoggingHook(),new AssistantToUser()
                ))
                .model(model)
                .memory(new InMemoryMemory())
                .build();

        Toolkit toolkit = new Toolkit();
        toolkit.createToolGroup("experts", "老师智能体", true);
        toolkit.registration()
                .subAgent(() -> ywls)
                .group("experts")
                .apply();
        toolkit.registration()
                .subAgent(() -> sxls)
                .group("experts")
                .apply();
        toolkit.registration()
                .subAgent(() -> yyls)
                .group("experts")
                .apply();

        System.out.println(JSONObject.toJSONString(toolkit));

--- 输出
{"activeGroups":["experts"],"toolNames":["call_____"],"toolSchemas":[{"description":"只处理英语相关问题","name":"call_____","parameters":{"type":"object","properties":{"session_id":{"description":"Session ID for multi-turn dialogue. Omit to start a NEW session. To CONTINUE an existing session and retain memory, you MUST extract the session_id from the previous response and pass it here.","type":"string"},"message":{"description":"Message to send to the agent","type":"string"}},"required":["message"]}}]}

### PR DESCRIPTION
**Pull request by jujn**
## Description

Close #1140 

This PR resolves tool name collision issues for SubAgents containing unsupported characters (e.g., spaces, non-English text). It introduces deterministic hashing and safe truncation, ensuring all automatically generated tool names are strictly unique and fully compliant with LLM API length constraints

## Checklist

Please check the following items before code is ready to be reviewed.

- [ ]  Code has been formatted with `mvn spotless:apply`
- [ ]  All tests are passing (`mvn test`)
- [ ]  Javadoc comments are complete and follow project conventions
- [ ]  Related documentation has been updated (e.g. links, examples, etc.)
- [ ]  Code is ready for review

### CODE REVIEW

File: agentscope-core/src/main/java/io/agentscope/core/tool/subagent/SubAgentTool.java [hunk 1]
```diff
@@ -388,24 +389,89 @@ private Map<String, Object> buildSchema() {
...
+        if (config.getToolName() != null && !config.getToolName().trim().isEmpty()) {
+            return config.getToolName().trim();
         }
-        // Generate from agent name: "ResearchAgent" -> "call_researchagent"
-        String agentName = agent.getName();
-        if (agentName == null || agentName.isEmpty()) {
+
+        if (agent.getName() == null || agent.getName().trim().isEmpty()) {
             return "call_agent";
         }
```
[the remark this answers is not in the document]
Comment (jujn) [reply agentscope-core/src/main/java/io/agentscope/core/tool/subagent/SubAgentTool.java:409]: The possibility of an agent without a name is low.

File: agentscope-core/src/main/java/io/agentscope/core/tool/subagent/SubAgentTool.java [hunk 2]
```diff
@@ -388,24 +389,91 @@ private Map<String, Object> buildSchema() {
...
+                        .replaceAll("[^a-z0-9_-]+", "_")
+                        .replaceAll("_+", "_")
+                        .replaceAll("^_+|_+$", "");
+
+        if (safePart.isEmpty()) {
+            safePart = "agent";
+        }
+
+        String resolvedName = prefix + safePart;
+        boolean isPureEnglish = originalName.toLowerCase().matches("^[a-z0-9_-]+$");
```
Comment (LearningGp) [inline agentscope-core/src/main/java/io/agentscope/core/tool/subagent/SubAgentTool.java]: isPureEnglish is false for "test agent" under the current implementation—this seems unexpected.

**Review by LearningGp — CHANGES_REQUESTED** [review]

File: agentscope-core/src/main/java/io/agentscope/core/tool/subagent/SubAgentTool.java (hunk 2 above)
Comment (jujn) [reply agentscope-core/src/main/java/io/agentscope/core/tool/subagent/SubAgentTool.java]: > isPureEnglish is false for "test agent" under the current implementation—this seems unexpected.

Thanks for your review. I have fixed it.

**Review by LearningGp — APPROVED** [review]
LGTM
